---

- name: install git
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: install nginx
  ansible.builtin.apt:
    name: "{{ nginxPackage }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
